### ISSUE TITLE
Add one-liner to ReadMe

### ISSUE THREAD

**Issue by DexterDreeeam** [Vinalti/Windows-Remove-Preinstalled-Apps#6]
`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; Invoke-WebRequest -Uri "https:///Vinalti/Windows-Remove-Preinstalled-Apps/main/remove_preinstalled_apps.ps1" -OutFile ./_tmp.ps1; powershell ./_tmp.ps1`

try this as one line

**Comment by Vinalti** [comment]
Right, that would work, the url would be `https://raw.githubusercontent.com/Vinalti/Windows-Remove-Preinstalled-Apps/main/remove_preinstalled_apps.ps1` also I added `&&` so in case of failure the commands stops.

```ps1
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser && Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Vinalti/Windows-Remove-Preinstalled-Apps/main/remove_preinstalled_apps.ps1" -OutFile ./_rpa.ps1 && ./_rpa.ps1 
```

I will update  the readme, thanks ! 👍

**Comment by Vinalti** [comment]
@DexterDreeeam Do you want to review the PR #7 ?
